# Generated by Django 3.2.3 on 2021-06-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapea',
            name='shapes_b',
            field=models.ManyToManyField(to='shapes.ShapeB'),
        ),
        migrations.CreateModel(
            name='ShapeC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('shapes_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapes.shapeb')),
            ],
        ),
    ]
