# Generated by Django 3.2.3 on 2021-06-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_auto_20210602_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapea',
            name='shapes_b',
            field=models.ManyToManyField(blank=True, to='shapes.ShapeB'),
        ),
    ]
