# Generated by Django 3.2.3 on 2021-06-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0003_alter_shapea_shapes_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapec',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shapec',
            name='size',
        ),
    ]
